### ISSUE TITLE
TODO list for draft paper

### ISSUE THREAD

**Issue by rrnewton** [tweag/linear-types#3]
Here's what we had from the last meeting... need to massage this into an up-to-date TODO list:

* Paper front end [Ryan & Simon ??]
  - [x] some various unfinished refactors/editing (e.g. renaming Bang)
  - [x] expand motivating example Msg=>PktH 
  - [ ] expand discussion of motivation [safe use of resources]
  - [x] (GC latency: forward pointers to Apps section.)
* [x] [Arnaud / Friday] Middle end: statics & dynamics sections.  
  - replace queue prims with PktH prims?
* New section (after sec 4): “Applications”.  
  - [x] [M & Arnaud] Develop the streaming/conduit examples.
  - [ ] Priority queue out-of-gc
    - [ ] Eval section? run benchmarks and write eval (behind schedule)
           This DOES NOT correspond to the minimal example from sec 1&2.  This is a fleshed out version.
        - Is traversal of queue that slow for GC or is the moving of the messages? Test with ints.
        - Make sure this matches the new version of the motivating example.
 * [x] [Mathieu] Related works: regions/sub-regions.
